version: '3.6'

services:
  # MySQL
  beer_inventory_service_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: beerinventoryservice
      MYSQL_HOST: localhost
      MYSQL_USER: beer_inventory_service
      MYSQL_PASSWORD: password
    ports:
        - "3309:3306"

    volumes:
      - ../scripts:/docker-entrypoint-initdb.d

  beer_inventory_service_adminer:
    image: adminer
    restart: always
    ports:
      - 8092:8080

#Volumes
volumes:
  dbdata:
    driver: local
